% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  12pt]{article}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother





\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 
\usepackage[]{natbib}
\bibliographystyle{agsm}


\addtolength{\oddsidemargin}{-.5in}%
\addtolength{\evensidemargin}{-1in}%
\addtolength{\textwidth}{1in}%
\addtolength{\textheight}{1.7in}%
\addtolength{\topmargin}{-1in}%
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Exploring k-Nearest Neighbors in Recommendation Systems},
  pdfauthor={Daizy Buluma},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}



\begin{document}


\def\spacingset#1{\renewcommand{\baselinestretch}%
{#1}\small\normalsize} \spacingset{1}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\title{\bf \textbf{Exploring k-Nearest Neighbors in Recommendation
Systems}}
\author{
Daizy Buluma\\
}
\maketitle

\bigskip
\bigskip
\begin{abstract}

\end{abstract}


\newpage
\spacingset{1.9} % DON'T change the spacing!


\section{\texorpdfstring{\textbf{Introduction}}{Introduction}}\label{introduction}

Today's digital world is overflowing with information, making it nearly
impossible for individuals to manually sift through the massive number
of available options. As a result, recommender systems have become
essential components of platforms such as Netflix, Amazon, Spotify, and
TikTok. Their primary goal is to filter vast collections of items such
as movies, products, songs, or videos, and present users with options
they are most likely to enjoy. These systems work by analyzing users'
preferences, past behaviors, and item characteristics through
interaction data such as impressions, clicks, ratings, likes, and
purchases \citep{ghosh2024}.

This paper focuses on the k-nearest neighbors (kNN) algorithm within the
context of recommendation systems. Although kNN is one of the more
straightforward algorithms in machine learning, it plays a foundational
role in collaborative filtering methods. kNN identifies users or items
that are most similar in behavior or preferences and bases predictions
on these neighbors. Its simplicity and intuitive mechanics make it
especially suitable for educational purposes and small scale
recommendation tasks.

Before exploring the details of kNN, this paper outlines the broader
landscape of recommendation systems to provide a foundation for
understanding how kNN fits into the larger family of recommendation
systems. The discussion then introduces and contrasts a different
recommendation approach, Singular Value Decomposition (SVD) to highlight
the strengths and weaknesses of kNN in practice.

Finally, the second half of the paper applies kNN to a real dataset to
build and evaluate a simple interactive recommender system so as
demonstrate how the method works in practice and gauge its performance.

\section{\texorpdfstring{\textbf{Overview of Recommender
Systems}}{Overview of Recommender Systems}}\label{overview-of-recommender-systems}

Recommendation systems work by estimating how much a user is likely to
enjoy an item they have not yet interacted with. They do this by
analyzing \textbf{user behavior}, such as past ratings or interactions
and \textbf{item features}, such as genre, creator, or textual
descriptions. The goal is to estimate a preference score, \({r}_{u,i}\)
which measures how likely user u is to enjoy item i. Recommendations are
then generated by selecting the items with the highest scores. More
details in section \ref{sec-rec} below.

To understand how k-nearest neighbors (kNN) fits into this broader
landscape, we will discuss two major families of recommendation
approaches: content-based approach and collaborative filtering (there
are hybrid recommenders too which combine the two approaches).

\subsection{\texorpdfstring{\textbf{Content-Based
Filtering}}{Content-Based Filtering}}\label{content-based-filtering}

Content-based recommender systems generate suggestions by comparing the
attributes of items a user previously liked to those of new items. These
attributes might include genres, keywords, textual descriptions, or
metadata. The item descriptions, which are labeled with ratings, are
used as training data to create a user-specific classification or
regression modeling problem. As Aggarwal explains, for each user the
training documents correspond to the descriptions of the items she has
bought or rated \citep[p.~14]{aggarwal2016}. For example, if a shopper
frequently purchases skincare products, the system recommends related
cosmetic items.

The underlying assumption is that user preferences are largely
consistent, and similar items will yield similar satisfaction
\citep{ghosh2024}. These models rely heavily on item features, making
them effective in domains where rich metadata is available.

\subsection{\texorpdfstring{\textbf{Collaborative
Filtering}}{Collaborative Filtering}}\label{collaborative-filtering}

Collaborative filtering takes a different approach by focusing on
patterns of behavior across users rather than item attributes. The key
assumption is that users who behaved similarly in the past will behave
similarly in the future. The main challenge in designing collaborative
filtering methods is that the underlying ratings matrices are sparse
(Most ratings are unspecified). However, in collaborative filtering
methods, these unspecified ratings can be imputed because the observed
ratings are often highly correlated across various users and items.
There are two main subtypes:

\subsubsection{\texorpdfstring{\textbf{Memory-Based
Methods}}{Memory-Based Methods}}\label{memory-based-methods}

Memory-based methods make predictions directly from observed ratings by
identifying similarities among users or items. kNN is the most common
example and can be further categorized into user-based kNN and
item-based kNN as we'll see in the next sections. The advantages of
memory-based techniques are that they are simple to implement and the
resulting recommendations are often easy to explain. On the other hand,
memory-based algorithms do not work very well with sparse ratings
matrices \citep{aggarwal2016}.

\subsubsection{\texorpdfstring{\textbf{Model-Based
Methods}}{Model-Based Methods}}\label{model-based-methods}

Model-based approaches use machine learning techniques to uncover latent
patterns in the rating matrix. Examples include Matrix factorization,
SVD and Neural networks. They tend to outperform memory-based methods on
large, sparse datasets but are less transparent to users and developers.
Notably, many hybrid recommenders combine kNN with model-based
techniques, such as SVD, to balance simplicity and predictive power
\citep{hssina2021}.

\section{K-Nearest Neighbors in Recommendation
Systems}\label{k-nearest-neighbors-in-recommendation-systems}

This section provides a deeper exposition of how kNN works, beginning
with motivation and intuition, then moving into supervised-learning kNN,
and finally examining how the algorithm is adapted for recommendation
systems. A worked toy example concludes the section to illustrate the
computations concretely.

\subsection{\texorpdfstring{\textbf{Motivation:} Why Neighbors Matter in
Recommendations}{Motivation: Why Neighbors Matter in Recommendations}}\label{motivation-why-neighbors-matter-in-recommendations}

The appeal of neighborhood‑based methods lies in their simplicity as
people with similar tastes tend to enjoy similar things. If two users
have consistently rated the same movies in comparable ways, then the
films one user has enjoyed but the other has not yet seen become strong
candidates for recommendation. This intuition, that preferences cluster
and can be shared across neighbors, forms the foundation of k‑Nearest
Neighbors (kNN) in recommender systems. By exploiting these local
patterns, kNN can generate useful predictions without the need for
complex modeling \citep{nikolakopoulos2021}.

\subsection{\texorpdfstring{\textbf{How kNN Works in Supervised
Learning}}{How kNN Works in Supervised Learning}}\label{how-knn-works-in-supervised-learning}

Before adapting kNN to recommender systems, it helps to first understand
how the algorithm works in its original setting. Unlike most algorithms
we've seen in class that estimate parameters or fit equations, kNN is a
``lazy learner'' (from wikipedia-should i cite this or add to the
integrity page). It stores the training data and defers computation
until a query arrives. When a new example is presented, the algorithm
measures its similarity to all stored examples, selects the \emph{k}
closest ones, and bases its prediction on their values.

In classification tasks, the new example is assigned to the majority
class among its neighbors. In regression, the prediction is the average
of their values. Weighted variants of kNN give greater influence to
closer neighbors, which reduces the impact of outliers. The choice of
\emph{k} is critical to prevent over or under fitting. Too small a
neighborhood makes the algorithm sensitive to noise, while too large a
neighborhood can dilute meaningful signals.

\begin{figure}[H]

{\centering \includegraphics[width=3.125in,height=3.125in]{images/knnimage1.png}

}

\caption{A simple illustration of kNN}

\end{figure}%

Because kNN does not assume any particular distribution of the data, it
is considered non‑parametric. This flexibility makes it easy to apply,
but it also introduces challenges in high‑dimensional spaces where
distances lose contrast, a phenomenon known as the curse of
dimensionality \citep[pg 19]{kramer2013}. (Still don't fully understand
the phenomenon. will return to explain when I do)

\subsection{\texorpdfstring{\textbf{How kNN Works in Recommender
Systems}}{How kNN Works in Recommender Systems}}\label{sec-rec}

In recommendation settings, the task is to predict missing entries in a
sparse user--item matrix of size (number of users) × (number of items).
Each row represents a user, each column an item, and most cells are
empty because users interact with only a small fraction of available
items. Below is an example of such matrix:

\begin{longtable}[]{@{}lllll@{}}
\toprule\noalign{}
User / Item & A & B & C & D \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
U1 & 4 & 4 & ? & 3 \\
U2 & 4 & 5 & 2 & ? \\
U3 & ? & 4 & 4 & 3 \\
U4 & 2 & ? & 5 & ? \\
\end{longtable}

Since most cells are empty, kNN adapts by computing similarities only on
overlapping ratings. This reliance on shared ratings is both a strength
because it uses actual behavioral similarity and a weakness because
sparsity may cause the similarities to be unreliable \citep{kramer2013}.
Two main variants are used:

\begin{itemize}
\tightlist
\item
  \textbf{User‑based kNN:} The system identifies the \emph{k} users most
  similar to the target user and infers preferences from their ratings.
  For example, if User 1 and User 2 have rated many of the same items
  similarly, then User 2's rating of a new item can help predict User
  1's interest.
\item
  \textbf{Item‑based kNN:} Instead of comparing users, the system finds
  items that consistently receive similar ratings across users. If Item
  A and Item B are rated alike by many users, then a user who liked Item
  A is predicted to enjoy Item B as well. Item‑based kNN is often more
  stable because item relationships remain consistent even as new users
  enter or leave the system. For this reason, modern commercial
  recommenders tend to use item-based kNN over user-based
  \citep{ricci2022}.
\end{itemize}

Similarity metrics are central to these computations. \textbf{Cosine
similarity} measures the angle between rating vectors, which makes it
resistant to differences in rating scales. \textbf{Pearson correlation}
adjusts for user biases by centering ratings around individual means.
\textbf{Adjusted cosine similarity} , which is commonly used in
item‑based kNN, subtracts user averages before computing similarity to
reduce the effect of rating habits \citep{aggarwal2016}. The similarity
scores typically range from -1 to 1. With -1 for vectors that are polar
opposites, 0 where there is no correlation and 1 for perfectly similar
vectors. (Should I include the formulas for computing the 3 similarity
metrics?)

Once similarities are computed, predictions are made using weighted
averages. In user-based approach, a simple average of is often
misleading because different users have different rating scales. One
user might rate movies from 3 to 5 stars, while another uses the full
1-to-5 range. To account for this, we use the deviation from each user's
average rating. For user‑based kNN, defines one formula for the
predicted rating of user (u) for item (i) as:

\[
P_{u,i} = \bar{r}_u + \frac{\sum_{v \in N} sim(u,v) \cdot (r_{v,i} - \bar{r}_v)}{\sum_{v \in N} |sim(u,v)|}
\]

Where;

\begin{itemize}
\item
  \(P_{u,i}\) is the predicted rating for the target user (u) on item
  (i).
\item
  \(\bar{r}_u\) is user (u)'s average rating. We add it at the end so
  that the prediction is returned to the user's original rating scale.
\item
  N is the neighborhood of users most similar to (u) who have rated item
  (i).
\item
  \(\text{sim}(u,v)\) is the similarity score between the target user
  (u) and a neighbor (v).
\item
  \(r_{v,i} - \bar{r}_v\) is neighbor (v)'s rating of item (i), centered
  by subtracting their own average rating. This expresses how much
  higher or lower than average the neighbor rated that item.
\item
  The denominator, \(\sum_{v \in N} |\text{sim}(u,v)|\), normalizes the
  weighted sum so that the prediction isn't inflated by the number or
  magnitude of similarity scores.
\end{itemize}

For item-based collaborative filtering, the logic mirrors the user-based
approach but is slightly simpler. To predict user (u)'s rating for item
(i), we look at the other items that user (u) has already rated. The
prediction is formed by taking a weighted average of those ratings,
where the weights come from the similarity between item (i) and each
neighboring item.

The formula is:

\[
P_{u,i} = \frac{\sum_{j \in N} sim(i,j) \cdot r_{u,j}}{\sum_{j \in N} |sim(i,j)|}
\]

Where;

\begin{itemize}
\item
  \(P_{u,i}\) is the predicted rating for user (u) on item (i).
\item
  N is the set of items most similar to item (i) that user (u) has
  already rated.
\item
  \(\text{sim}(i,j)\) is the similarity between the target item (i) and
  a neighbor item (j).
\item
  \(r_{u,j}\) is the rating user (u) gave to item (j).
\end{itemize}

One important detail is that we do not need to adjust for user averages
here. Because all ratings involved in the calculation come from the same
user, their rating scale is already consistent across items. As a
result, the weighted average directly reflects how much the user liked
similar items, making the item-based formulation slightly simpler than
the user-based version.

Both formulas and breakdowns were derived from \citep{apxml2025}.

A critical design choice in kNN is the size of the neighborhood, denoted
by k. The number of neighbors directly influences the bias--variance
trade‑off in predictions. With very small k, the recommender becomes
highly sensitive to noise in individual ratings, which can reduce
accuracy. With very large k, the recommender averages across many
dissimilar users or items, diluting meaningful signals. In practice, the
optimal k is determined empirically by evaluating accuracy metrics such
as RMSE (Root Mean Squared Error), MAE (Mean Absolute Error), Precision,
and Recall across different values of k. Cross‑validation is commonly
used to select k, ensuring that the chosen neighborhood size generalizes
well to unseen data \citep{aggarwal2016, hahsler2022}.

\section{\texorpdfstring{\textbf{Performance Metrics in Recommender
Systems}}{Performance Metrics in Recommender Systems}}\label{performance-metrics-in-recommender-systems}

Evaluating recommender systems requires multiple complementary metrics,
since a single measure rarely captures the full picture of performance.
The choice of \emph{k} in kNN is closely linked to these metrics, as
neighborhood size influences both prediction accuracy and recommendation
quality.

\begin{itemize}
\tightlist
\item
  \textbf{Prediction Accuracy (ratings‑based):}\\
  The first question is: \emph{does the system predict ratings
  correctly?}

  \begin{itemize}
  \tightlist
  \item
    \textbf{RMSE (Root Mean Squared Error):} penalizes large errors more
    heavily, making it sensitive to extreme mispredictions.\\
  \item
    \textbf{MAE (Mean Absolute Error):} interpretable as the average
    deviation between predicted and actual ratings.\\
    These metrics assess how close predicted ratings are to true
    ratings. Smaller neighborhoods may reduce RMSE if neighbors are
    highly similar, but risk instability; larger neighborhoods smooth
    predictions but can inflate MAE by averaging across dissimilar users
    \citep{aggarwal2016}.
  \end{itemize}
\item
  \textbf{Recommendation Accuracy (top‑N lists):}\\
  The second question is: \emph{does the system recommend items that
  users actually like?}

  \begin{itemize}
  \tightlist
  \item
    \textbf{Precision:} the proportion of recommended items that are
    truly relevant.\\
  \item
    \textbf{Recall:} the proportion of relevant items successfully
    recommended.\\
  \item
    \textbf{F1 Score:} harmonic mean of precision and recall, balancing
    both.\\
    Here, \emph{k} influences the diversity and relevance of the
    recommendation list. A small \emph{k} may yield highly precise but
    narrow recommendations, while a large \emph{k} increases recall but
    risks recommending irrelevant items \citep{ricci2022}.
  \end{itemize}
\item
  \textbf{Ranking Quality:}\\
  The third question is: \emph{are the most relevant items ranked near
  the top of the list?}

  \begin{itemize}
  \tightlist
  \item
    \textbf{ROC curves and AUC:} visualize the trade‑off between true
    positives and false positives.\\
  \item
    \textbf{Precision--Recall curves:} highlight performance in sparse
    datasets where relevant items are rare.\\
    These measures are particularly important in large catalogs, where
    the majority of items are irrelevant to any given user
    \citep{hahsler2022}.
  \end{itemize}
\end{itemize}

By reporting both prediction and recommendation accuracy, researchers
can capture not only how well the system predicts ratings but also how
useful its recommendations are to end‑users. Cross‑validation is
typically used to select the optimal \emph{k} by comparing these metrics
across folds, ensuring that the chosen neighborhood size generalizes
well to unseen data \citep{hssina2021}.

\subsubsection{\texorpdfstring{\textbf{Toy
Example}}{Toy Example}}\label{toy-example}

We finish with a toy example adapted from Aggawral's book to emphasize
idea. Consider a simple dataset of three users and three movies:

\begin{longtable}[]{@{}llll@{}}
\toprule\noalign{}
User & A & B & C \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
U1 & 5 & 4 & ? \\
U2 & 4 & 4 & 2 \\
U3 & 1 & 1 & 1 \\
\end{longtable}

\textbf{Entries:} Ratings on a 1--5 scale. The ``?'' is the missing
rating we want to predict (U1's rating for Movie C).

First, we compute the similarity between Movie C and movies that U1 has
already rated (A and B) using cosine similarity.

\begin{itemize}
\tightlist
\item
  \textbf{Movie A ratings vector:} {[}5, 4, 1{]} from U1, U2, U3\\
\item
  \textbf{Movie B ratings vector:} {[}4, 4, 1{]} from U1, U2, U3\\
\item
  \textbf{Movie C ratings vector:} {[}?, 2, 1{]} → U1's rating is
  missing, so we only use U2 and U3: {[}2, 1{]}
\end{itemize}

Now,

To compute \textbf{sim(A, C)}, we compare Movie A's ratings from U2 and
U3 ({[}4, 1{]}) with Movie C's ratings from U2 and U3 ({[}2, 1{]}).

\[
sim(A,C) = \frac{(4 \cdot 2) + (1 \cdot 1)}{\sqrt{4^2+1^2} \cdot \sqrt{2^2+1^2}} \approx 0.98
\]

To compute \textbf{sim(B, C)}, we compare Movie B's ratings from U2 and
U3 ({[}4, 1{]}) with Movie C's ratings from U2 and U3 ({[}2, 1{]}).

\[
sim(B,C) = \frac{(4 \cdot 2) + (1 \cdot 1)}{\sqrt{4^2+1^2} \cdot \sqrt{2^2+1^2}} \approx 0.96
\]

These values (0.98 and 0.96) show that Movies A and B are both highly
similar to Movie C therefore we use their ratings to calculate the
predicted rating for Movie C.

Plugging in values into the Item-Based formula we get:

\[
P_{U1,C} = \frac{(0.98 \cdot 5) + (0.96 \cdot 4)}{0.98 + 0.96} = \frac{4.9 + 3.84}{1.94} \approx 4.55
\]

U1's predicted rating for Movie C is about 4.6 stars. The recommendation
system system expects U1 to enjoy Movie C almost as much as Movies A and
B.

\subsection{\texorpdfstring{\textbf{Strengths and Weaknesses of kNN in
Recommendation
Systems}}{Strengths and Weaknesses of kNN in Recommendation Systems}}\label{strengths-and-weaknesses-of-knn-in-recommendation-systems}

As we established in the sections above, kNN requires no training phase,
is easy to explain, and works well for small or dense datasets where
overlaps are plentiful. Its neighbor‑driven reasoning makes it
particularly suitable for educational settings and for systems where
interpretability is valued.

However, kNN also has notable weaknesses. Its reliance on overlapping
ratings makes it vulnerable to sparsity, and its computational cost
grows quickly with dataset size. In high‑dimensional rating matrices,
distance metrics can become unreliable therefore reducing accuracy.
These limitations explain why kNN is often used as a baseline method,
while large‑scale commercial systems rely on more advanced model‑based
approaches such as matrix factorization or deep learning
(\citet{hssina2021}).

\section{\texorpdfstring{\textbf{Comparison to a Model-Based Method
(SVD)}}{Comparison to a Model-Based Method (SVD)}}\label{comparison-to-a-model-based-method-svd}

While kNN provides an intuitive way to generate recommendations by
looking at neighbors, it struggles with sparse data and scalability. To
address these challenges, recommender systems often turn to
\textbf{model-based methods}. One of the most influential is
\textbf{Singular Value Decomposition (SVD)}, a matrix factorization
technique that has become central to modern recommendation engines
(\citet{hssina2021}; \citet{apxml2025}).

\subsection{What SVD Does (Very
High-Level)}\label{what-svd-does-very-high-level}

SVD takes the large (millions of ratings), sparse user--item ratings
matrix (R) and decomposes it into three smaller matrices:

\[
R = U \cdot \Sigma \cdot V^T
\]

\begin{itemize}
\tightlist
\item
  \textbf{U:} Represents users in terms of hidden ``taste dimensions''
  (latent factors).\\
\item
  \(Sigma\): Diagonal matrix of singular values, showing which factors
  are most important.\\
\item
  \(V^T\): Represents items in terms of the same latent factors.
\end{itemize}

By keeping only the top k singular values, SVD compresses the ratings
matrix into a lower-dimensional representation. This reveals hidden
patterns of preference for example, one factor might capture a user's
tendency toward action/sci‑fi movies, while another captures
romance/musicals. Predictions for missing ratings are made by combining
a user's latent profile with an item's latent profile
(\citet{apxml2025}).

This approach differs fundamentally from kNN. While kNN Predictions rely
on local neighborhoods and finds similar users or items directly from
observed ratings, SVD learns a compressed representation of the entire
dataset and its predictions come from latent factors rather than direct
neighbors.

kNN is transparent and easy to interpret (``your neighbor liked this, so
you might too''), but it struggles with sparsity and scalability. SVD,
by contrast, is less interpretable because latent factors are abstract,
yet it generalizes better and scales efficiently to millions of users
and items.

The trade-offs between the two methods can be summarized as follows:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2535}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3803}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3662}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Aspect
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
kNN (Memory-Based)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
SVD (Model-Based)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Mechanism} & Direct similarity between users/items & Factorizes
ratings matrix: \(R = U \Sigma V^T\) \\
\textbf{Data requirement} & Works directly on raw ratings & Needs enough
data to learn latent factors \\
\textbf{Scalability} & Struggles with millions of users/items &
Efficient at large scale once trained \\
\textbf{Cold start problem} & Severe (new users/items have no neighbors)
& Still an issue, but generalizes better \\
\textbf{Accuracy} & Good for small datasets, local patterns & Better for
large datasets, global patterns \\
\textbf{Interpretability} & Easy to explain (``neighbors liked it'') &
Harder to explain (latent factors abstract) \\
\end{longtable}

For small educational datasets or applications where interpretability is
paramount, kNN remains a useful choice. Its neighbor-driven reasoning
makes it particularly suitable for teaching and for systems where
transparency is valued. For commercial platforms like Netflix or
Spotify, where accuracy and scalability matter most, SVD is the dominant
approach. By compressing massive rating matrices into latent factors,
SVD not only improves predictive accuracy but also makes large-scale
recommendation feasible. In short, kNN thrives on simplicity and
transparency, while SVD thrives on efficiency and predictive power,
together illustrating the evolution of recommender systems from
neighbor-driven reasoning to model-based learning.

\section{\texorpdfstring{\textbf{Application: Building a Simple
Recommendation Engine with
kNN}}{Application: Building a Simple Recommendation Engine with kNN}}\label{application-building-a-simple-recommendation-engine-with-knn}

The dataset used in this study consists of three interconnected tables:

\begin{itemize}
\tightlist
\item
  \textbf{Books dataset}: Contains metadata for each book, including
  ISBN, title, and author.\\
\item
  \textbf{Ratings dataset}: Records user interactions with books, where
  each entry includes a \texttt{user\_id}, \texttt{book\_id}, and a
  numerical rating on a 0--10 scale. Ratings of zero represent implicit
  interactions (presence in the system without explicit feedback).\\
\item
  \textbf{Users dataset}: Provides demographic information for each
  user, including \texttt{user\_id}, age, and location.
\end{itemize}

Together, these tables form the basis for constructing a user--item
ratings matrix. The ratings table links users to books, while the books
and users tables provide contextual metadata. After joining the three
datasets, the combined table contains over 380,000 ratings from
approximately 68,000 users on nearly 150,000 books.

This raw dataset is highly sparse which means most users rate only a
handful of books, and most books receive very few ratings. Such sparsity
is typical in recommendation systems and motivates the filtering and
preprocessing steps described below.

\subsection{\texorpdfstring{\textbf{Data
Preprocessing}}{Data Preprocessing}}\label{data-preprocessing}

We begin by loading the three source files --- books, ratings, and users
--- and cleaning them to retain only the relevant attributes. For books,
we keep the ISBN, title, and author; for ratings, we rename the columns
to \texttt{user\_id}, \texttt{book\_id}, and \texttt{book\_rating}; and
for users, we retain the \texttt{user\_id} and \texttt{location}.
Duplicate entries are removed to ensure consistency.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{books }\OtherTok{\textless{}{-}}\NormalTok{ books }\SpecialCharTok{|\textgreater{}} 
         \FunctionTok{select}\NormalTok{(ISBN,Book.Title,Book.Author) }\SpecialCharTok{|\textgreater{}} 
         \FunctionTok{rename}\NormalTok{(}
           \AttributeTok{book\_title =}\NormalTok{ Book.Title,}
           \AttributeTok{author =}\NormalTok{ Book.Author,}
           \AttributeTok{book\_id =}\NormalTok{ ISBN}
\NormalTok{         )}

\NormalTok{ratings }\OtherTok{\textless{}{-}}\NormalTok{ ratings }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{rename}\NormalTok{(}
    \AttributeTok{user\_id =}\NormalTok{ User.ID,}
    \AttributeTok{book\_rating =}\NormalTok{ Book.Rating,}
    \AttributeTok{book\_id =}\NormalTok{ ISBN}
\NormalTok{  )}
\NormalTok{users }\OtherTok{\textless{}{-}}\NormalTok{ users }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{select}\NormalTok{(User.ID, Location) }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{rename}\NormalTok{(}
    \AttributeTok{user\_id =}\NormalTok{ User.ID,}
    \AttributeTok{location =}\NormalTok{ Location)}
\end{Highlighting}
\end{Shaded}

The three datasets are then joined into a single ratings table,
providing a unified view of user--book interactions.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ratings\_full }\OtherTok{\textless{}{-}}\NormalTok{ ratings }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{inner\_join}\NormalTok{(books, }
             \AttributeTok{by =} \StringTok{"book\_id"}\NormalTok{)}\SpecialCharTok{|\textgreater{}}  
  \FunctionTok{inner\_join}\NormalTok{(users, }
             \AttributeTok{by =} \StringTok{"user\_id"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Ratings in the full dataset range from 0 to 10. However summary
statistics revealed that more than half of the ratings in the dataset
were equal to zero.

\begin{verbatim}

     0      1      2      3      4      5      6      7      8      9     10 
647294   1481   2375   5118   7617  45355  31687  66402  91804  60778  71225 
\end{verbatim}

The zero values were intepreted as not genuine ratings, but as
indicators that a user had interacted with a book without providing
explicit feedback. In other words, a 0 marks presence in the system
rather than an evaluation of preference. Because collaborative filtering
relies explicit numerical ratings to compute similarities and generate
predictions, including these implicit entries would bias the
distribution and distort accuracy measures such as RMSE and MAE. For
this reason, I excluded all records with a rating of zero.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Drop records with rating = 0}
\NormalTok{ratings\_clean }\OtherTok{\textless{}{-}}\NormalTok{ ratings\_full }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{filter}\NormalTok{(book\_rating }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

To address sparsity, we only include users and books with sufficiently
active profiles. This ensures that similarity calculations are based on
sufficiently active profiles.

\pandocbounded{\includegraphics[keepaspectratio]{FinalProjectPaper_files/figure-pdf/unnamed-chunk-7-1.pdf}}

The histogram of ratings per user shows the distribution of how many
books each user has rated in the dataset. Because the x‑axis is plotted
on a log scale, we can see that the majority of users contributed only a
small number of ratings, while a much smaller group of highly active
users contributed thousands. This long‑tailed pattern is typical of
recommendation datasets: most users interact with only a handful of
items, whereas a few ``power users'' generate a disproportionately large
number of ratings. The skewed distribution highlights the sparsity
problem in collaborative filtering, since many users provide too little
data to compute reliable similarities. It also motivates the decision to
set a threshold for ``active'' users, ensuring that the recommender
system is trained on profiles with enough ratings to support meaningful
recommendations.

This same pattern was found with the items with most books being rated
only once or twice, while a small number of popular titles received
hundreds of ratings. To mitigate this, we introduced a threshold line at
10 ratings, excluding books with fewer than 10 ratings from the final
dataset. This cutoff ensures that the recommender system is trained on
items with sufficient feedback to support meaningful recommendations.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Set thresholds }
\NormalTok{min\_user\_ratings }\OtherTok{\textless{}{-}} \DecValTok{10}   \CommentTok{\# active users}
\NormalTok{min\_item\_ratings }\OtherTok{\textless{}{-}} \DecValTok{10}   \CommentTok{\# active books}

\CommentTok{\# Filter ratings dataset to keep only active users and active books}
\NormalTok{ratings\_filtered }\OtherTok{\textless{}{-}}\NormalTok{ ratings\_clean }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{inner\_join}\NormalTok{(user\_counts }\SpecialCharTok{|\textgreater{}} \FunctionTok{filter}\NormalTok{(n\_user }\SpecialCharTok{\textgreater{}=}\NormalTok{ min\_user\_ratings), }\AttributeTok{by =} \StringTok{"user\_id"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{inner\_join}\NormalTok{(item\_counts }\SpecialCharTok{|\textgreater{}} \FunctionTok{filter}\NormalTok{(n\_item }\SpecialCharTok{\textgreater{}=}\NormalTok{ min\_item\_ratings), }\AttributeTok{by =} \StringTok{"book\_id"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The filtering process substantially reduced the dataset, as shown in
Table below.

\begin{longtable}[]{@{}cccc@{}}
\caption{Dataset size before and after filtering
thresholds}\tabularnewline
\toprule\noalign{}
Stage & Users & Books & Ratings \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Stage & Users & Books & Ratings \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Before filtering & 68091 & 149836 & 383842 \\
After filtering & 6318 & 5438 & 87178 \\
\end{longtable}

Before applying thresholds, the dataset contained 68,091 users, 149,836
books and 383,842 ratings. After requiring each user and each book to
have at least 10 ratings, the dataset was reduced to 6,318 users, 5,438
books, and 87,178 ratings. This reduction highlights the sparsity of the
original dataset, where most users and books had very few ratings. By
retaining only active users and active books, the final dataset provides
a denser interaction matrix that supports more reliable similarity
calculations and improves the robustness of the recommender system.

\subsection{\texorpdfstring{\textbf{Matrix
Transformation}}{Matrix Transformation}}\label{matrix-transformation}

Collaborative filtering requires a user--item matrix. The filtered
ratings are reshaped into wide format, converted to a matrix, and then
cast into a \texttt{realRatingMatrix} object, the format expected by
\texttt{recommenderlab}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# reshape into wide format (users as rows, books as columns)}
\NormalTok{rating\_wide }\OtherTok{\textless{}{-}}\NormalTok{ ratings\_filtered }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{select}\NormalTok{(user\_id, book\_id, book\_rating) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ book\_id, }\AttributeTok{values\_from =}\NormalTok{ book\_rating)}
\CommentTok{\# convert to matrix (drop user\_id column)}
\NormalTok{rating\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(rating\_wide[,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{])}
\CommentTok{\# convert to realRatingMatrix}
\NormalTok{rating\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{as}\NormalTok{(rating\_matrix, }\StringTok{"realRatingMatrix"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{\texorpdfstring{\textbf{Implementing kNN \& Model
Evaluation}}{Implementing kNN \& Model Evaluation}}\label{implementing-knn-model-evaluation}

Once the ratings matrix was transformed into a realRatingMatrix, the
next step was to implement a k‑Nearest Neighbors recommender. In
recommenderlab, this is achieved with the Recommender() function,
specifying ``UBCF'' (user‑based collaborative filtering) or ``IBCF''
(item‑based collaborative filtering).

To evaluate performance, two complementary schemes can be employed. A
simple train/test split was first used to illustrate the mechanics of
recommender evaluation: the model is trained on 70\% of the data,
predictions are generated for the ``known'' portion of the test set, and
accuracy is computed against the ``unknown'' ratings. This one‑time
split provides a clear demonstration of how training, prediction, and
evaluation interact in practice.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Simple train/test split (80/20)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{495}\NormalTok{)}
\NormalTok{scheme\_split }\OtherTok{\textless{}{-}} \FunctionTok{evaluationScheme}\NormalTok{(rating\_matrix, }
                                 \AttributeTok{method=}\StringTok{"split"}\NormalTok{, }
                                 \AttributeTok{train=}\FloatTok{0.8}\NormalTok{, }
                                 \AttributeTok{given=}\DecValTok{10}\NormalTok{, }
                                 \AttributeTok{goodRating=}\DecValTok{6}\NormalTok{)}
\CommentTok{\# Train UBCF on training set}
\NormalTok{ubcf\_model }\OtherTok{\textless{}{-}} \FunctionTok{Recommender}\NormalTok{(}\FunctionTok{getData}\NormalTok{(scheme\_split, }\StringTok{"train"}\NormalTok{), }
                          \AttributeTok{method=}\StringTok{"UBCF"}\NormalTok{,}
                          \AttributeTok{parameter=}\FunctionTok{list}\NormalTok{(}
                            \AttributeTok{nn=}\DecValTok{30}\NormalTok{, }\AttributeTok{method=}\StringTok{"Cosine"}\NormalTok{, }\AttributeTok{normalize=}\StringTok{"center"}\NormalTok{))}
\CommentTok{\# Predict ratings for known test set}
\NormalTok{ubcf\_pred }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(ubcf\_model, }\FunctionTok{getData}\NormalTok{(scheme\_split, }\StringTok{"known"}\NormalTok{), }
                     \AttributeTok{type=}\StringTok{"ratings"}\NormalTok{)}
\CommentTok{\# Evaluate against unknown ratings}
\NormalTok{metrics }\OtherTok{\textless{}{-}} \FunctionTok{calcPredictionAccuracy}\NormalTok{(ubcf\_pred, }\FunctionTok{getData}\NormalTok{(scheme\_split, }\StringTok{"unknown"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Because a single split can be sensitive to how the data is partitioned,
the analysis relied primarily on k‑fold cross‑validation for robust
model selection. In this scheme, the dataset is divided into five folds;
each fold is used once as a test set while the remaining folds serve as
training data. Results are averaged across folds, providing a more
reliable estimate of performance. Cross‑validation was used to compare
different neighborhood sizes (k) and similarity measures (Cosine
vs.~Pearson), ensuring that the chosen configuration generalizes well to
unseen data \citep{aggarwal2016, ricci2022}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 5{-}fold cross{-}validation for exploratory runs}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{495}\NormalTok{)}
\NormalTok{scheme\_cv\_light }\OtherTok{\textless{}{-}} \FunctionTok{evaluationScheme}\NormalTok{(rating\_matrix, }
                                    \AttributeTok{method=}\StringTok{"cross{-}validation"}\NormalTok{, }
                                    \AttributeTok{k=}\DecValTok{5}\NormalTok{, }
                                    \AttributeTok{given=}\DecValTok{10}\NormalTok{, }
                                    \AttributeTok{goodRating=}\DecValTok{6}\NormalTok{)}

\CommentTok{\# Smaller grid: just two algorithms to compare}
\NormalTok{algorithms\_grid\_light }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}
  \StringTok{"UBCF\_cosine\_k10"} \OtherTok{=} \FunctionTok{list}\NormalTok{(}\AttributeTok{name=}\StringTok{"UBCF"}\NormalTok{, }
                           \AttributeTok{param=}\FunctionTok{list}\NormalTok{(}\AttributeTok{nn=}\DecValTok{10}\NormalTok{, }\AttributeTok{method=}\StringTok{"Cosine"}\NormalTok{, }
                                      \AttributeTok{normalize=}\StringTok{"center"}\NormalTok{)),}
  \StringTok{"UBCF\_pearson\_k30"} \OtherTok{=} \FunctionTok{list}\NormalTok{(}\AttributeTok{name=}\StringTok{"UBCF"}\NormalTok{, }
                            \AttributeTok{param=}\FunctionTok{list}\NormalTok{(}\AttributeTok{nn=}\DecValTok{30}\NormalTok{, }\AttributeTok{method=}\StringTok{"Pearson"}\NormalTok{, }
                                       \AttributeTok{normalize=}\StringTok{"center"}\NormalTok{))}
\NormalTok{)}
\CommentTok{\# Ratings{-}based CV }
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{495}\NormalTok{)}
\NormalTok{cv\_results\_ratings\_light }\OtherTok{\textless{}{-}} \FunctionTok{evaluate}\NormalTok{(scheme\_cv\_light, }
\NormalTok{                                     algorithms\_grid\_light, }
                                     \AttributeTok{type=}\StringTok{"ratings"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
UBCF run fold/sample [model time/prediction time]
     1  [0.002sec/8.11sec] 
     2  [0.001sec/7.602sec] 
     3  [0.002sec/7.444sec] 
     4  [0.001sec/7.729sec] 
     5  [0.002sec/8.061sec] 
UBCF run fold/sample [model time/prediction time]
     1  [0.001sec/5.801sec] 
     2  [0.001sec/5.513sec] 
     3  [0.001sec/5.736sec] 
     4  [0.001sec/5.429sec] 
     5  [0.001sec/5.409sec] 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Summarize RMSE/MAE}
\NormalTok{ratings\_summary\_light }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(}\FunctionTok{lapply}\NormalTok{(cv\_results\_ratings\_light, avg), }
                                   \AttributeTok{.id=}\StringTok{"model"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Based on the exploratory cross‑validation results, user‑based
collaborative filtering with cosine similarity and a neighborhood size
of k = 10 was selected as the final model. To quantify its predictive
accuracy, the model was evaluated using a held‑out scheme, yielding
performance metrics such as RMSE, MAE, and Precision/Recall at different
recommendation list lengths. These results provide a robust estimate of
how well the chosen configuration generalizes to unseen data.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Evaluation scheme for reproducibility (train/test split)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{495}\NormalTok{)}
\NormalTok{scheme\_final }\OtherTok{\textless{}{-}} \FunctionTok{evaluationScheme}\NormalTok{(rating\_matrix, }
                                 \AttributeTok{method=}\StringTok{"split"}\NormalTok{, }
                                 \AttributeTok{train=}\FloatTok{0.8}\NormalTok{, }
                                 \AttributeTok{given=}\DecValTok{10}\NormalTok{, }
                                 \AttributeTok{goodRating=}\DecValTok{6}\NormalTok{)}
\CommentTok{\# Train final model on training set}
\NormalTok{final\_model\_eval }\OtherTok{\textless{}{-}} \FunctionTok{Recommender}\NormalTok{(}
  \FunctionTok{getData}\NormalTok{(scheme\_final, }\StringTok{"train"}\NormalTok{),}
  \AttributeTok{method    =} \StringTok{"UBCF"}\NormalTok{,}
  \AttributeTok{parameter =} \FunctionTok{list}\NormalTok{(}\AttributeTok{nn =} \DecValTok{10}\NormalTok{, }\AttributeTok{method =} \StringTok{"Cosine"}\NormalTok{, }\AttributeTok{normalize =} \StringTok{"center"}\NormalTok{)}
\NormalTok{)}

\CommentTok{\# {-}{-}{-}{-} Ratings{-}based evaluation {-}{-}{-}{-}}
\NormalTok{final\_pred\_ratings }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(}
\NormalTok{  final\_model\_eval, }
  \FunctionTok{getData}\NormalTok{(scheme\_final, }\StringTok{"known"}\NormalTok{), }
  \AttributeTok{type=}\StringTok{"ratings"}\NormalTok{)}
\NormalTok{metrics\_ratings }\OtherTok{\textless{}{-}} \FunctionTok{calcPredictionAccuracy}\NormalTok{(}
\NormalTok{  final\_pred\_ratings, }
  \FunctionTok{getData}\NormalTok{(scheme\_final, }\StringTok{"unknown"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

The final model (UBCF with cosine similarity, k = 10) achieved an RMSE
of 1.88, MSE of 3.53, and MAE of 1.38 on the held‑out evaluation scheme.
These values indicate that predictions deviate from true ratings by
approximately 1--2 points on average, which is consistent with
performance reported in similar collaborative filtering studies. To
contextualize these results, we compared the chosen kNN approach against
a baseline matrix factorization method (SVD). This comparison highlights
the relative strengths of neighborhood‑based collaborative filtering in
capturing user preferences within the dataset.

\begin{longtable}[]{@{}cccc@{}}
\caption{Performance comparison of UBCF and SVD models}\tabularnewline
\toprule\noalign{}
Model & RMSE & MSE & MAE \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Model & RMSE & MSE & MAE \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
UBCF (Cosine, k=10) & 1.89 & 3.57 & 1.41 \\
SVD (k=50) & 1.63 & 2.66 & 1.21 \\
\end{longtable}

As can be seen in the table above SVD achieved lower error values across
all metrics (RMSE = 1.63, MSE = 2.66, MAE = 1.21). These results confirm
the broader finding in recommender system literature that matrix
factorization methods such as SVD typically outperform
neighborhood‑based approaches in terms of predictive accuracy.
Nevertheless, the kNN framework remains valuable for pedagogical
purposes, as its mechanics are more transparent and intuitive.

\subsection{\texorpdfstring{\textbf{Interactive Shiny
Application}}{Interactive Shiny Application}}\label{interactive-shiny-application}

To illustrate how recommendation works in practice, we developed an
interactive Shiny application that implements the final User‑Based
Collaborative Filtering (UBCF) model with cosine similarity. The app
provides a hands‑on interface where users can select a specific user ID,
adjust the neighborhood size \(k\) and specify the number of
recommendations to generate. The output is a ranked table of book titles
and authors, accompanied by preference scores that reflect the relative
strength of each recommendation. These scores are not bounded by the
original 1--10 rating scale but serve as indicators of predicted
interest, with higher values corresponding to stronger recommendations.

The application also includes a User Lookup tab, which retrieves
demographic information such as age and location from the users file.
This feature allows researchers to contextualize recommendation patterns
by examining how user characteristics relate to the books suggested.
Screenshots of both tabs are included below to demonstrate the workflow:
one showing the recommendation interface with sliders and output table,
and another highlighting the user lookup functionality.

\pandocbounded{\includegraphics[keepaspectratio]{images/recommendation.png}}
Figure 5 illustrates the Recommendations tab, where users can adjust the
neighborhood size and number of recommendations.

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{images/userlookup.png}}

}

\caption{user lookup interface}

\end{figure}%

\section{\texorpdfstring{\textbf{Appendix}}{Appendix}}\label{appendix}

\pandocbounded{\includegraphics[keepaspectratio]{FinalProjectPaper_files/figure-pdf/unnamed-chunk-18-1.pdf}}


\renewcommand\refname{\textbf{References}}
\bibliography{bibliography.bib}



\end{document}
