---
title: "Final Project - Integrity Page"
author: "Daizy Buluma"
date: today
format: pdf
editor: visual
---

```{r}
#| label: load-packages
#| include: false

library(mosaic)
library(tidyverse)
library(mdsr)
# add other packages here!
```

# Practicing Academic Integrity

If you worked with others or used resources outside of provided course material, such as Generative AI, (anything besides our textbook, course materials in the repo, labs, R help menu) to help complete this assignment, please acknowledge them below using a bulleted list. Remember that according to our class framework, if you engage with Generative AI tools, the tool and date of use must be listed here, and then a complete record of the chat history must be appended to the assignment.

<!-- ~~~~~~~~~~~~~~~~ YOU MAY BEGIN EDITING BELOW THIS LINE ~~~~~~~~~~~~~~~~ -->

*I acknowledge the following individuals with whom I worked on this assignment:*

Name(s) and how they assisted you

-   Asked my friend (Shekinah Ninziza) who is not in our class to read through my paper and let me know if it made sense to a non-statistical audience. This was in case I end up submitting the paper for a competition. I have since decided not to.

-   Vanesa was my peer reviewer.

*I used the following sources to help complete this assignment:*

Source(s) and where you used them

-   Used Generative AI for:

    -   Troubleshooting a fatal error I had in R after installing the package required for my application. Date: 12/11/2025 Link to the chat: <https://chatgpt.com/share/693b8a5d-e260-800c-adbc-46919be189b4>

    -   Seeking an easier explanation for SVD as I was having a hard time understanding it from my selected sources. Date: 12/3/2025 Link to chat: <https://copilot.microsoft.com/shares/aVmJ7BmoKz1BLK9vaCuSG>

    -   Streamlining a paragraph that I felt was repetitive Date: 12/1/2025 Link to chat: <https://copilot.microsoft.com/shares/TBGpdustRoSU5qydY5DKn> (Ended up not using it)

    -   Troubleshooting an error I was having with my shiny app Date: 12/14/2025 Link to chat: <https://share.google/aimode/DRMfTAagiD4PbodSw>

    -   Making a reasonable project timeline. I unfortunately lost the link to this chat. But my prompt was something along the lines of : *I have a month to complete this project and these are the activities I plan to do. Please space them out in a reasonable way. I expect the last weeks to be hectic because of competing deadlines with my other classes for finals.*

-   I looked through multiple kaggle projects to get a sense of the workflow of recommender system projects:

    -   <https://www.kaggle.com/code/rushiekarteekchalla/amazon-product-recommendation-system>

    -   <https://www.kaggle.com/code/shawamar/product-recommendation-system-for-e-commerce>

    -   <https://www.kaggle.com/datasets/arashnic/book-recommendation-dataset>

        (Almost all of them used python)

-   Watched this video to learn how to make web app. I eventually decided to use an interactive Shiny App instead:<https://www.youtube.com/watch?v=Ne-mxM4lDUE&list=PLkz_y24mlSJYWa_JEjptWvwXToNNXIXOp&index=8>

-   Used my past projects and a STAT‑230 cheat sheet as references for LaTeX formatting of equations (My paper had about 3 equations only)

-   Used STAT-231 project to refresh on Shiny App.

# Note

Data sources and sources for your exposition on your new topic should be cited in your report, so they don't need citations here. This is for when you look up code errors or how to do something in ggplot2, etc.
