<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daizy Buluma">
<meta name="dcterms.date" content="2025-10-06">

<title>YTD Analysis of E-commerce Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="TPproject_files/libs/clipboard/clipboard.min.js"></script>
<script src="TPproject_files/libs/quarto-html/quarto.js"></script>
<script src="TPproject_files/libs/quarto-html/popper.min.js"></script>
<script src="TPproject_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="TPproject_files/libs/quarto-html/anchor.min.js"></script>
<link href="TPproject_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="TPproject_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="TPproject_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="TPproject_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="TPproject_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><strong>1. Introduction</strong></a></li>
  <li><a href="#data-summary-and-cleaning" id="toc-data-summary-and-cleaning" class="nav-link" data-scroll-target="#data-summary-and-cleaning"><strong>2. Data Summary and Cleaning</strong></a>
  <ul class="collapse">
  <li><a href="#data-cleaning-process" id="toc-data-cleaning-process" class="nav-link" data-scroll-target="#data-cleaning-process"><strong>2.1 Data Cleaning Process</strong></a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><strong>3. Exploratory Data Analysis</strong></a>
  <ul class="collapse">
  <li><a href="#monthly-sales-trends" id="toc-monthly-sales-trends" class="nav-link" data-scroll-target="#monthly-sales-trends"><strong>3.1 Monthly Sales Trends</strong></a></li>
  <li><a href="#top-countries-by-revenue" id="toc-top-countries-by-revenue" class="nav-link" data-scroll-target="#top-countries-by-revenue"><strong>3.2 Top Countries by Revenue</strong></a></li>
  <li><a href="#customer-spending-behavior" id="toc-customer-spending-behavior" class="nav-link" data-scroll-target="#customer-spending-behavior"><strong>3.3 Customer Spending Behavior</strong></a></li>
  </ul></li>
  <li><a href="#regression-analysis" id="toc-regression-analysis" class="nav-link" data-scroll-target="#regression-analysis"><strong>4. Regression Analysis</strong></a>
  <ul class="collapse">
  <li><a href="#fitting-a-multiple-linear-regression-model" id="toc-fitting-a-multiple-linear-regression-model" class="nav-link" data-scroll-target="#fitting-a-multiple-linear-regression-model">Fitting A Multiple Linear Regression Model</a></li>
  <li><a href="#results-and-interpretation" id="toc-results-and-interpretation" class="nav-link" data-scroll-target="#results-and-interpretation"><strong>4.5 Results and Interpretation</strong></a></li>
  <li><a href="#key-predictors" id="toc-key-predictors" class="nav-link" data-scroll-target="#key-predictors"><strong>Key Predictors</strong></a></li>
  <li><a href="#regional-effects" id="toc-regional-effects" class="nav-link" data-scroll-target="#regional-effects"><strong>Regional Effects</strong></a></li>
  <li><a href="#model-fit" id="toc-model-fit" class="nav-link" data-scroll-target="#model-fit"><strong>Model Fit</strong></a></li>
  </ul></li>
  <li><a href="#interactive-dashboard-visualization" id="toc-interactive-dashboard-visualization" class="nav-link" data-scroll-target="#interactive-dashboard-visualization"><strong>5. Interactive Dashboard Visualization</strong></a></li>
  <li><a href="#discussion-and-business-implications" id="toc-discussion-and-business-implications" class="nav-link" data-scroll-target="#discussion-and-business-implications"><strong>6. Discussion and Business Implications</strong></a>
  <ul class="collapse">
  <li><a href="#model-interpretation" id="toc-model-interpretation" class="nav-link" data-scroll-target="#model-interpretation"><strong>Model Interpretation</strong></a></li>
  <li><a href="#insights-from-the-dashboard" id="toc-insights-from-the-dashboard" class="nav-link" data-scroll-target="#insights-from-the-dashboard"><strong>Insights from the Dashboard</strong></a></li>
  <li><a href="#business-implications" id="toc-business-implications" class="nav-link" data-scroll-target="#business-implications"><strong>Business Implications</strong></a></li>
  </ul></li>
  <li><a href="#conclusion-and-future-work" id="toc-conclusion-and-future-work" class="nav-link" data-scroll-target="#conclusion-and-future-work"><strong>7. Conclusion and Future Work</strong></a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">YTD Analysis of E-commerce Data</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Daizy Buluma </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 6, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This project explores e-commerce sales performance through the lens of applied business intelligence, combining statistical modeling in R with interactive visualization in Tableau. Using a dataset of over half a million online transactions, the analysis aimed to identify the key factors influencing purchase amounts and to derive insights for strategic decision-making.</p>
<p>After comprehensive data cleaning and transformation, exploratory analysis revealed that most sales originated from European markets, though transactions from Asia and other regions tended to have higher per-order values. A multiple linear regression model identified Quantity and Unit Price as the strongest predictors of total transaction value, while regional effects further highlighted differences in consumer behavior across markets.</p>
<p>The Tableau dashboard complements these findings by visualizing revenue trends, return rates, and customer performance, enabling dynamic exploration of sales patterns and business KPIs. Together, the statistical and visual analyses demonstrate how data-driven methods can enhance understanding of sales performance and inform actionable business strategies.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction"><strong>1. Introduction</strong></h2>
<p>In today’s data-driven retail environment, organizations increasingly rely on business intelligence (BI) tools to gain insights from large volumes of transactional data. This project applies BI principles to an <strong>e-commerce dataset</strong> containing over half a million transaction records, with the goal of uncovering patterns in sales, customer behavior, and product performance.</p>
<p>The dataset provides detailed information on transactions, including invoice numbers, product descriptions, quantities, unit prices, customer identifiers, and countries of origin. These attributes enable comprehensive analysis across multiple dimensions of business performance—such as revenue trends, customer segmentation, and return behaviors.</p>
<p>The primary objective of this project is to demonstrate applied <strong>business intelligence and analytics skills</strong> through both <strong>statistical modeling in R</strong> and <strong>interactive visualization in Tableau</strong>. The project proceeds in two major phases:</p>
<ol type="1">
<li><strong>Data Analytics in R</strong> – involving data wrangling, exploratory analysis, and regression modeling to identify the factors that predict total purchase amount per transaction.</li>
<li><strong>Interactive Dashboard Development in Tableau</strong> – translating analytical findings into dynamic visualizations that provide actionable insights for decision-makers.</li>
</ol>
<p>Through this integrated approach, the project highlights how statistical and visual analytics complement each other in transforming raw data into meaningful business insights. The final deliverable combines analytical rigor with interactive storytelling—demonstrating the full BI workflow from data preparation to insight communication.</p>
</section>
<section id="data-summary-and-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="data-summary-and-cleaning"><strong>2. Data Summary and Cleaning</strong></h2>
<p>The dataset contains 541,909 transaction records and 8 variables: <code>InvoiceNo</code>, <code>StockCode</code>, <code>Description</code>, <code>Quantity</code>, <code>InvoiceDate</code>, <code>UnitPrice</code>, <code>CustomerID</code>, and <code>Country</code>. Each observation represents a single product purchased (or returned) as part of a customer invoice. A preliminary summary reveals several important characteristics and data quality issues:</p>
<ul>
<li><strong>InvoiceNo, StockCode, Description, and Country</strong> are stored as text fields, which is expected since they represent transaction identifiers, product descriptions, or categorical values.</li>
<li><strong>Quantity</strong> ranges from <strong>-80,995 to 80,995</strong>. Negative values represent product returns or cancellations, while most transactions involve small positive quantities (median = 3, 75th percentile = 10).</li>
<li><strong>InvoiceDate</strong> is currently stored as a character variable and requires conversion to a proper datetime format for time-based analysis.</li>
<li><strong>UnitPrice</strong> ranges from <strong>-11,062 to 38,970</strong>. Negative or zero prices likely indicate errors or adjustments, whereas the majority of products are low-priced items (median = 2.1, mean = 4.6).</li>
<li><strong>CustomerID</strong> ranges from 12,346 to 18,287 but has <strong>135,080 missing values</strong>, representing about <strong>25% of transactions</strong>. These may correspond to guest checkouts or incomplete records.</li>
</ul>
<p>Overall, the dataset is rich in detail but requires substantial cleaning before statistical analysis. Specifically, returns/cancellations, extreme outliers, and missing customer identifiers must be addressed to ensure reliable modeling and dashboard insights.</p>
<section id="data-cleaning-process" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-process"><strong>2.1 Data Cleaning Process</strong></h3>
<p>During data preparation, several cleaning and transformation steps were performed to ensure analytical accuracy. The <em>InvoiceDate</em> field, initially stored as text, was converted into a proper datetime format to support time-based analyses such as monthly trends and year-to-date performance. Invalid or extreme entries in <em>Quantity</em> and <em>UnitPrice</em> were identified and removed — negative quantities were treated as returns, and only reasonable price values (between 0 and 10,000) were retained. Missing or invalid <em>CustomerID</em> values were replaced with “Guest,” allowing inclusion of anonymous transactions without conflating them with registered customers. Text variables, including product descriptions and country names, were standardized to title case and cleaned of extra spaces to avoid grouping inconsistencies. Duplicate records sharing the same <em>InvoiceNo</em> and <em>StockCode</em> were also removed to prevent double-counting. Finally, several new features were engineered: <em>TotalPrice</em> (calculated as <em>Quantity × UnitPrice</em>) to represent transaction value, and <em>TransactionMonth</em> and <em>TransactionYear</em> to facilitate temporal analysis.</p>
</section>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis"><strong>3. Exploratory Data Analysis</strong></h2>
<p>After cleaning the dataset, the next step was to conduct a thorough exploratory analysis to understand the key patterns, trends, and relationships in the data. The goal of this stage is to inform the regression modeling and identify metrics that can be highlighted in the Tableau dashboard.</p>
<section id="monthly-sales-trends" class="level3">
<h3 class="anchored" data-anchor-id="monthly-sales-trends"><strong>3.1 Monthly Sales Trends</strong></h3>
<p>To identify seasonal patterns and sales dynamics over time, monthly sales totals were aggregated using the <code>TransactionMonth</code> variable. A line chart was plotted to visualize total sales per month. This allows us to detect peaks and troughs in sales, which may correspond to seasonal demand, promotional campaigns, or other temporal effects.</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="TPproject_files/figure-html/ggplot-1-1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Monthly revenue displays a clear cyclical pattern, with sales peaks toward the end of the year—consistent with holiday-season demand. Lower mid-year sales suggest slower retail activity during non-promotional months. Such temporal insights can guide inventory management, staffing, and promotional planning.</p>
</section>
<section id="top-countries-by-revenue" class="level3">
<h3 class="anchored" data-anchor-id="top-countries-by-revenue"><strong>3.2 Top Countries by Revenue</strong></h3>
<p>To identify geographic drivers of sales, total revenue was aggregated by country and ranked.</p>
<div class="cell" data-layout-align="left">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="TPproject_files/figure-html/ggplot-2-1.png" class="img-fluid quarto-figure quarto-figure-left figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>The <strong>United Kingdom</strong> overwhelmingly dominates total sales, accounting for the majority of transactions. Other European countries, including France, the Netherlands, and Germany, form the secondary market tier. This geographic concentration indicates a primarily UK-based e-commerce operation with limited but growing international reach.</p>
</section>
<section id="customer-spending-behavior" class="level3">
<h3 class="anchored" data-anchor-id="customer-spending-behavior"><strong>3.3 Customer Spending Behavior</strong></h3>
<p>Customer-level analysis helps reveal purchasing patterns and engagement heterogeneity. The scatterplot below plots total spending against the number of orders per customer.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TPproject_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot exhibits a positive association between the number of orders and total spending, with a few high-value customers contributing disproportionately to total revenue.</p>
<p>These insights provide an empirical foundation for the subsequent <strong>regression modeling</strong>, which investigates predictors of transaction value and customer spending. Overall, the exploratory analysis provided a clear understanding of the dataset’s structure, key trends, and business-relevant metrics. These insights will guide the regression modeling and form the foundation for the interactive dashboard, ensuring that the project highlights actionable business intelligence.</p>
<p>For extended descriptive summaries and return-rate analyses, see Appendices A and B.</p>
</section>
</section>
<section id="regression-analysis" class="level2">
<h2 class="anchored" data-anchor-id="regression-analysis"><strong>4. Regression Analysis</strong></h2>
<p>The goal of this regression analysis is to identify the key factors that influence the <strong>total purchase amount per transaction</strong> within the e-commerce dataset. This helps quantify how variables such as <strong>quantity purchased</strong>, <strong>unit price</strong>, and <strong>country</strong> predict the total value of a transaction. This model provides insights into spending behavior, potential pricing effects, and country-level demand variation.</p>
<p>Before fitting the model, the dataset was filtered to include only valid, non-cancellation transactions and positive values of price and quantity.</p>
<section id="fitting-a-multiple-linear-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-multiple-linear-regression-model">Fitting A Multiple Linear Regression Model</h3>
<p>The dependent variable in this model is <strong>TotalPrice</strong>, defined as the product of <code>Quantity × UnitPrice</code>. Four predictor variables were selected based on their theoretical and business relevance:</p>
<ul>
<li><strong>Quantity</strong> – Number of units purchased per transaction.</li>
<li><strong>UnitPrice</strong> – Price per individual product unit.</li>
<li><strong>Country</strong> – Country where the transaction occurred (categorical variable).</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TotalPrice ~ Quantity + UnitPrice + Continent, data = regression_data)

Residuals:
   Min     1Q Median     3Q    Max 
 -4502     -5     -4      1  38183 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           1.048669   3.778573   0.278  0.78137    
Quantity              1.147220   0.002626 436.929  &lt; 2e-16 ***
UnitPrice             1.099713   0.003768 291.878  &lt; 2e-16 ***
ContinentAsia        12.687133   4.543195   2.793  0.00523 ** 
ContinentEurope       2.562528   3.779674   0.678  0.49779    
ContinentMiddle East  7.642961   5.125038   1.491  0.13588    
ContinentOther       16.706943   4.042908   4.132 3.59e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 71.89 on 519591 degrees of freedom
Multiple R-squared:  0.3441,    Adjusted R-squared:  0.3441 
F-statistic: 4.543e+04 on 6 and 519591 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>To verify model validity, residual diagnostics were performed to test the assumptions of linearity, constant variance, and normality.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="TPproject_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:mosaic':

    deltaMethod, logit</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>              GVIF Df GVIF^(1/(2*Df))
Quantity  1.004500  1        1.002247
UnitPrice 1.000855  1        1.000427
Continent 1.004509  4        1.000563</code></pre>
</div>
</div>
<p>The diagnostic plots show no major violations of model assumptions. Residuals are approximately homoscedastic, and the QQ-plot indicates that the normality assumption holds reasonably well. Variance Inflation Factor (VIF) values for all predictors were below 5, suggesting no concerning multicollinearity</p>
</section>
<section id="results-and-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="results-and-interpretation"><strong>4.5 Results and Interpretation</strong></h3>
<p>The final regression model is: [ = 1.05 + 1.15() + 1.10() + 12.69() + 2.56() + 7.64() + 16.71() + ]</p>
<p>The regression model examined how <code>Quantity</code>, <code>UnitPrice</code>, and <code>Continent</code> influence the total transaction value (<code>TotalPrice</code>). The model is statistically significant overall, <strong>F(6, 519,591) = 45,430, p &lt; 0.001</strong>, with an <strong>adjusted R² of 0.344</strong>, indicating that approximately <strong>34.4% of the variation</strong> in transaction value is explained by these predictors.</p>
</section>
<section id="key-predictors" class="level3">
<h3 class="anchored" data-anchor-id="key-predictors"><strong>Key Predictors</strong></h3>
<p>Both <strong>Quantity</strong> and <strong>UnitPrice</strong> are strong, statistically significant, and positive predictors of total sales (p &lt; 0.001).</p>
<ul>
<li>The coefficient for <code>Quantity</code> (<strong>β = 1.147</strong>) suggests that for each additional unit purchased, total transaction value increases by approximately <strong>1.15 monetary units</strong>, holding all else constant.</li>
<li>The coefficient for <code>UnitPrice</code> (<strong>β = 1.10</strong>) indicates that for every one-unit increase in product price, total transaction value increases by about <strong>1.10 units</strong>, reflecting the direct impact of pricing on revenue.</li>
</ul>
<p>These findings confirm that sales value is primarily driven by both the volume of products purchased and their individual prices — a relationship consistent with standard business expectations.</p>
</section>
<section id="regional-effects" class="level3">
<h3 class="anchored" data-anchor-id="regional-effects"><strong>Regional Effects</strong></h3>
<p>The categorical variable <code>Continent</code> captures geographic differences in transaction values relative to the baseline (Americas).</p>
<ul>
<li><strong>Asia (β = 12.69, p = 0.005)</strong> and <strong>Other (β = 16.71, p &lt; 0.001)</strong> regions show significantly higher average transaction values compared to the baseline.</li>
<li><strong>Europe (β = 2.56, p = 0.498)</strong> and <strong>Middle East (β = 7.64, p = 0.136)</strong> are not statistically significant, suggesting relatively similar transaction values to the reference group.</li>
</ul>
<p>These results indicate that transactions in Asian and smaller “Other” markets (e.g., smaller or niche countries) tend to involve higher-value purchases, while European and Middle Eastern transactions do not differ meaningfully from those in the Americas after accounting for quantity and price.</p>
</section>
<section id="model-fit" class="level3">
<h3 class="anchored" data-anchor-id="model-fit"><strong>Model Fit</strong></h3>
<p>The <strong>residual standard error of 71.89</strong> indicates moderate unexplained variation — reasonable for large-scale transaction data with diverse products and prices. The <strong>adjusted R² of 0.344</strong> confirms that the model captures the main quantitative and regional patterns in sales but that additional unobserved factors (such as product category, time of day, or customer type) may also influence transaction values.While the model explains a substantial portion of variation in transaction value (Adjusted R² = 0.344), several factors not captured in the data likely influence total sales, such as product category, promotional discounts, and customer demographics. Therefore, the model should be interpreted as capturing broad business-level relationships rather than predicting individual transaction values with precision.</p>
</section>
</section>
<section id="interactive-dashboard-visualization" class="level2">
<h2 class="anchored" data-anchor-id="interactive-dashboard-visualization"><strong>5. Interactive Dashboard Visualization</strong></h2>
<p>To complement the statistical modeling, an interactive Tableau dashboard was developed to visualize key e-commerce performance metrics. The dashboard provides an intuitive way to explore sales trends, customer purchasing behavior, and product-level performance across time and regions.</p>
<p>The dashboard integrates the cleaned dataset used in the regression model and presents metrics such as:</p>
<ul>
<li><strong>Total Sales and Year-to-Date Growth:</strong> Summarizes overall revenue and its change relative to the previous year.</li>
<li><strong>Sales by Continent and Country:</strong> Highlights market distribution and reveals Europe as the dominant contributor to revenue.</li>
<li><strong>Monthly Sales and Returns Trends:</strong> Shows seasonality in transactions and product returns over time.</li>
<li><strong>Top Products and Customers:</strong> Identifies the highest-grossing products and key customer segments driving revenue.</li>
</ul>
<p>These interactive components allow users to filter results dynamically by date, region, and product category, providing a business intelligence perspective on the data beyond the regression results.</p>
<p>The dashboard was built using <strong>Tableau Desktop</strong> and published on <strong>Tableau Public</strong> for interactive access. You can explore it below:</p>
<p><em>Note:</em> The embedded dashboard below may take a few seconds to load depending on your network connection. For faster access, you can view it directly on Tableau Public using this link: <a href="https://public.tableau.com/shared/GGJS4CRS7?:display_count=n&amp;:origin=viz_share_link"><strong>Open Dashboard on Tableau Public</strong></a></p>
<div class="tableauPlaceholder" id="viz1759780353177" style="position: relative">
  <noscript>
    <a href="#">
      <img alt="ECOMMERCE SALES DASHBOARD | YTD SALES ANALYSIS" src="https://public.tableau.com/static/images/GG/GG944YBFC/1_rss.png" style="border: none">
    </a>
  </noscript>

  <object class="tableauViz" style="display:none;">
    <param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F">
    <param name="embed_code_version" value="3">
    <param name="path" value="shared/GG944YBFC">
    <param name="toolbar" value="yes">
    <param name="static_image" value="https://public.tableau.com/static/images/GG/GG944YBFC/1.png">
    <param name="animate_transition" value="yes">
    <param name="display_static_image" value="yes">
    <param name="display_spinner" value="yes">
    <param name="display_overlay" value="yes">
    <param name="display_count" value="yes">
    <param name="language" value="en-US">
  </object>
</div>

<script type="text/javascript">
  var divElement = document.getElementById('viz1759780353177');
  var vizElement = divElement.getElementsByTagName('object')[0];

  if (divElement.offsetWidth > 800) { 
    vizElement.style.width = '1200px';
    vizElement.style.height = '827px';
  } else if (divElement.offsetWidth > 500) { 
    vizElement.style.width = '1200px';
    vizElement.style.height = '827px';
  } else { 
    vizElement.style.width = '100%';
    vizElement.style.height = '2227px';
  }

  var scriptElement = document.createElement('script');
  scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';
  vizElement.parentNode.insertBefore(scriptElement, vizElement);
</script>

</section>
<section id="discussion-and-business-implications" class="level2">
<h2 class="anchored" data-anchor-id="discussion-and-business-implications"><strong>6. Discussion and Business Implications</strong></h2>
<p>The regression model and the Tableau dashboard collectively provide a comprehensive understanding of the key factors driving e-commerce performance.</p>
<section id="model-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="model-interpretation"><strong>Model Interpretation</strong></h3>
<p>The regression analysis showed that both <strong>Quantity</strong> and <strong>Unit Price</strong> are highly significant predictors of total revenue. As expected, higher quantities and prices lead to larger transaction values. The coefficients indicate that for every one-unit increase in quantity, total sales increase by approximately <strong>1.15 units</strong>, holding other variables constant. Similarly, each one-unit increase in unit price raises total revenue by about <strong>1.10 units</strong>, confirming a strong, direct relationship between product price and sales value.</p>
<p>Regional effects also emerged: transactions from <strong>Asia</strong> and <strong>Other regions</strong> (which include smaller markets outside Europe and the Middle East) had significantly higher sales values compared to the baseline category. In contrast, European sales—while dominant in volume—did not differ significantly in per-transaction value, suggesting that European buyers purchase more frequently but in smaller amounts per order.</p>
</section>
<section id="insights-from-the-dashboard" class="level3">
<h3 class="anchored" data-anchor-id="insights-from-the-dashboard"><strong>Insights from the Dashboard</strong></h3>
<p>The interactive dashboard complements these findings by offering a visual perspective on trends and distributions.</p>
<ul>
<li><strong>Sales Concentration:</strong> Europe accounts for the majority of transactions, confirming the regression finding that quantity drives revenue more than price in this market.</li>
<li><strong>Temporal Trends:</strong> Monthly sales visualizations show peak activity during the holiday season, followed by a drop early in the year, suggesting strong seasonality.</li>
<li><strong>Returns and Refunds:</strong> The dashboard highlights specific months and products with unusually high return rates, which can help identify potential quality or fulfillment issues.</li>
<li><strong>Customer Segmentation:</strong> The “Top Customers” view reveals a small group of repeat buyers contributing disproportionately to revenue—an insight that could guide retention strategies.</li>
</ul>
</section>
<section id="business-implications" class="level3">
<h3 class="anchored" data-anchor-id="business-implications"><strong>Business Implications</strong></h3>
<p>From a strategic perspective, these findings suggest several actionable takeaways:</p>
<ol type="1">
<li><strong>Leverage High-Value Markets:</strong> Asia and smaller “Other” regions represent opportunities for premium-priced products or localized marketing efforts.</li>
<li><strong>Optimize Product Mix in Europe:</strong> Since transaction frequency is high but per-order value is lower, strategies such as bundling or upselling could improve margins.</li>
<li><strong>Seasonal Inventory Planning:</strong> Retailers should stock up in advance of seasonal peaks and prepare return-handling capacity post-holiday.</li>
<li><strong>Customer Retention Focus:</strong> Targeting high-value repeat customers through loyalty programs could yield significant revenue stability.</li>
</ol>
<p>Together, the statistical model and dashboard visualization illustrate how <strong>data-driven decision-making</strong> can uncover patterns that are not immediately visible through raw figures alone.</p>
</section>
</section>
<section id="conclusion-and-future-work" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-and-future-work"><strong>7. Conclusion and Future Work</strong></h2>
<p>This project demonstrated the application of <strong>business intelligence and statistical analysis</strong> to uncover actionable insights from e-commerce transaction data. Using R for data wrangling, exploratory analysis, and regression modeling, and Tableau for interactive visualization, the study integrated analytical and visual storytelling approaches that mirror real-world data analytics workflows.</p>
<p>The regression analysis revealed that <strong>Quantity</strong> and <strong>Unit Price</strong> are the strongest predictors of transaction value, reaffirming their central role in revenue generation. Regional analysis suggested that while Europe dominates total sales, other regions such as <strong>Asia</strong> and <strong>smaller global markets</strong> exhibit higher transaction values, highlighting opportunities for market diversification. The accompanying Tableau dashboard provided an intuitive interface for stakeholders to explore these findings dynamically, bridging the gap between statistical output and managerial decision-making.</p>
<p>Despite its strengths, the study has certain limitations. The dataset lacked detailed customer demographics, marketing spend, and product category granularity—factors that could further enhance predictive power. Additionally, the regression model, while statistically robust, captures only a portion of the variation in sales behavior.</p>
<p>For <strong>future work</strong>, several extensions are possible:</p>
<ol type="1">
<li><strong>Incorporate temporal forecasting</strong> (e.g., ARIMA or Prophet models) to predict future sales trends.</li>
<li><strong>Develop customer segmentation models</strong> (such as k-means clustering) to identify distinct buying behaviors.</li>
<li><strong>Integrate external factors</strong> like holidays, promotions, or macroeconomic indicators to contextualize trends.</li>
<li>Expand the <strong>Tableau dashboard</strong> to include predictive KPIs or real-time sales feeds for ongoing business monitoring.</li>
</ol>
<p>In conclusion, this project underscores the value of <strong>data-driven decision-making</strong> in e-commerce. By combining R’s analytical power with Tableau’s visual interactivity, businesses can move beyond descriptive reporting to uncover predictive and prescriptive insights that drive smarter strategy and measurable performance improvement.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>